# Generated by Django 3.2.3 on 2021-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ydate', models.DateField(verbose_name='收據日期')),
                ('itemname', models.CharField(max_length=200, verbose_name='項目名稱')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='收據號碼')),
                ('shop', models.CharField(blank=True, max_length=200, null=True, verbose_name='店家名稱')),
                ('price', models.IntegerField(verbose_name='價格')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
    ]
