# Generated by Django 3.2.3 on 2021-05-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twinbird', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wonder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xdate', models.DateField(verbose_name='評估日期')),
                ('note', models.CharField(max_length=200, verbose_name='項目名稱')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='需求來源')),
                ('xrange', models.CharField(blank=True, max_length=200, null=True, verbose_name='價格區間')),
                ('twinbirdx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twinbird.twinbird')),
            ],
            options={
                'db_table': 'wonders',
            },
        ),
    ]
