# Generated by Django 3.2.3 on 2021-05-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twinbird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wonderid', models.IntegerField(verbose_name='評估id')),
                ('wondernote', models.CharField(blank=True, max_length=200, null=True, verbose_name='評估備註')),
                ('dogid', models.IntegerField(verbose_name='收據日期id')),
                ('dogitemname', models.CharField(blank=True, max_length=200, null=True, verbose_name='收據日期備註')),
                ('catid', models.IntegerField(verbose_name='收據店家欄位id')),
                ('catitemname', models.CharField(blank=True, max_length=200, null=True, verbose_name='收據店家欄位備註')),
                ('eggid', models.IntegerField(verbose_name='收據價錢欄位id')),
                ('eggitemname', models.CharField(blank=True, max_length=200, null=True, verbose_name='收據價錢欄位備註')),
            ],
            options={
                'db_table': 'twinbirds',
            },
        ),
    ]
