# Generated by Django 3.2.3 on 2021-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twinbird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twinbird',
            name='catid',
            field=models.IntegerField(blank=True, null=True, verbose_name='收據店家欄位id'),
        ),
        migrations.AlterField(
            model_name='twinbird',
            name='eggid',
            field=models.IntegerField(blank=True, null=True, verbose_name='收據價錢欄位id'),
        ),
    ]
